package com.anz.usersdirectoryapp.di

import com.anz.usersdirectoryapp.data.remote.UserApiService
import com.anz.usersdirectoryapp.data.repository.UserDetailRepository
import com.anz.usersdirectoryapp.data.repository.UserListRepository
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import javax.inject.Singleton

private const val BASE_URL = "https://fake-json-api.mock.beeceptor.com"

/**
 * Hilt module that provides singleton dependencies for the entire application.
 */
@Module
@InstallIn(SingletonComponent::class)
object AppModule {

    /**
     * Provides a singleton instance of [Retrofit] for network operations.
     */
    @Provides
    @Singleton
    fun providesRetrofit() : Retrofit {
       return Retrofit.Builder()
           .baseUrl(BASE_URL)
           .addConverterFactory(GsonConverterFactory.create())
           .build()
    }

    /**
     * Provides a singleton instance of [UserApiService] generated by Retrofit.
     */
    @Provides
    @Singleton
    fun provideUserApiService(retrofit: Retrofit) : UserApiService {
        return retrofit.create(UserApiService::class.java)
    }

    /**
     * Provides a singleton instance of [UserListRepository].
     */
    @Provides
    @Singleton
    fun provideUserListRepository(userApiService: UserApiService): UserListRepository {
        return UserListRepository(userApiService)
    }

    /**
     * Provides a singleton instance of [UserDetailRepository].
     */
    @Provides
    @Singleton
    fun provideUserDetailRepository(userApiService: UserApiService) : UserDetailRepository {
        return UserDetailRepository(userApiService)
    }
}